# Generated by Django 4.0.3 on 2022-04-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('avaliation', models.IntegerField(default=0)),
                ('qtd_avaliation', models.IntegerField(default=0)),
                ('total_stars', models.FloatField(default=0)),
                ('media', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
