# Generated by Django 4.0.3 on 2022-04-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='avaliation',
        ),
        migrations.AddField(
            model_name='livros',
            name='aval',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
    ]
