# Generated by Django 4.0.3 on 2022-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_remove_livros_avaliation_livros_aval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='qtd_avaliation',
            field=models.FloatField(default=0),
        ),
    ]
