# Generated by Django 4.0.3 on 2022-04-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_alter_livros_qtd_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='aval',
            field=models.FloatField(choices=[('1', '1.0'), ('2', '2.0'), ('3', '3.0'), ('4', '4.0'), ('5', '5.0')], default=0),
        ),
    ]
