# Generated by Django 4.0.3 on 2022-04-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_books_carrinho_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Livros',
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinho'},
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='titulo',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
