# Generated by Django 4.0.3 on 2022-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_rename_books_livros_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
