# Generated by Django 4.0.3 on 2022-04-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0007_carrinho_quantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'ordering': ['-media'], 'verbose_name_plural': 'Livros'},
        ),
    ]
