# Generated by Django 4.0.3 on 2022-04-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0008_alter_livros_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Books',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Livros'},
        ),
    ]
