# Generated by Django 4.0.3 on 2022-04-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0009_rename_livros_books_alter_books_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Livros',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
