# Generated by Django 4.0.3 on 2022-04-29 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0011_alter_livros_aval_alter_livros_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='valor',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='titulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livraria.livros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='media',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='qtd_avaliation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='total_stars',
            field=models.FloatField(default=0, null=True),
        ),
    ]
