# Generated by Django 4.0.3 on 2022-04-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0012_remove_carrinho_foto_remove_carrinho_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='aval',
            field=models.FloatField(),
        ),
    ]
