# Generated by Django 4.0.3 on 2022-04-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0013_alter_livros_aval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='aval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='qtd_avaliation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='total_stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
