# Generated by Django 4.0.3 on 2022-04-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0014_alter_livros_aval_alter_livros_qtd_avaliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='aval',
            field=models.IntegerField(null=True),
        ),
    ]
