# Generated by Django 4.0.3 on 2022-04-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0015_alter_livros_aval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='aval',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
