# Generated by Django 4.0.3 on 2022-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0016_alter_livros_aval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinho'},
        ),
        migrations.RenameField(
            model_name='carrinho',
            old_name='titulo',
            new_name='livros',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livros',
            name='media',
            field=models.IntegerField(null=True),
        ),
    ]
