# Generated by Django 4.0.3 on 2022-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0017_alter_carrinho_options_rename_titulo_carrinho_livros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
