# Generated by Django 4.0.3 on 2022-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0019_remove_livros_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
