# Generated by Django 4.0.3 on 2022-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0020_alter_livros_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='media',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
