# Generated by Django 4.0.3 on 2022-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('aval', models.IntegerField(default=0, null=True)),
                ('qtd_avaliation', models.IntegerField(default=0, null=True)),
                ('total_stars', models.IntegerField(default=0, null=True)),
                ('media', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Livro',
            },
        ),
    ]
